# Generated by Django 5.1.3 on 2024-12-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pb_meme_forge',
            field=models.IntegerField(blank=True, help_text='Personalbest for MemeForge gamemode.', null=True),
        ),
    ]
