# Generated by Django 5.1.3 on 2024-12-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_forge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memetemplate',
            name='image_url',
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='alternative_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='file_size',
            field=models.CharField(default='0 KB', max_length=15),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='format',
            field=models.CharField(choices=[('jpg', 'JPG'), ('png', 'PNG'), ('gif', 'GIF')], default='jpg', max_length=10),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='image_url_local',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='image_url_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='text_boxes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='memetemplate',
            index=models.Index(fields=['name'], name='meme_forge__name_54d74f_idx'),
        ),
    ]
