# Generated by Django 5.1.3 on 2024-11-28 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='game_mode',
        ),
        migrations.RemoveField(
            model_name='lobbyplayer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='lobbyplayer',
            name='username',
        ),
        migrations.AddField(
            model_name='lobbyplayer',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lobbyplayer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
