# Generated by Django 5.1.3 on 2024-12-09 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_remove_lobby_game_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbyplayer',
            name='lobby',
        ),
        migrations.RemoveField(
            model_name='lobbyplayer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lobby',
        ),
        migrations.DeleteModel(
            name='LobbyPlayer',
        ),
    ]
